openapi: 3.0.0
info:
  title: Documentación de los boletos
  version: 1.0.0
  description: Ejemplos para las URL de los boletos
servers:
  - description: Sevidor local para correr la api
    url: http://localhost:8080

paths:
  /api/boleto:
    get:
      summary: Listado de todos los boletos comprados o creados
      responses:
          200:
            description: Todo OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    properties:
                      nombre:
                        type: string
                        example: mauricio matuz
                      correo:
                        type: string
                        example: matamau@gmail.com
                      contraseña:
                        type: string
                        example: contraseña
                      usuario:
                        type: string
                        example: maumatuz
          404:
            description: Pagina no encontrada
            content:
              application/json:
                schema:
                  type: string
                  example: { "message": "Error 404. Pagina no encontrada." }

  /api/registrar/boleto:
    post:
      summary: Vender (crear) boletos
      requestBody:
        