openapi: 3.0.0
info:
  version: 1.0.0
  title: Documentación de los usuarios
  description: Ejemplos para las URL de los usuarios para usarlo en back
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  # para resubir
  - description: servidor local para correr la api
    url: http://34.225.239.102

paths:
  /api/autobus:
    get:
      summary: Lista de los autobuses registrados

      responses:
        200:
          description: Todo OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    clave:
                      type: string
                      example: 1LJ123sQWE
                    placa:
                      type: string
                      example: JKHA-123
                    numasientos:
                      type: integer
                      example: 40
                    fecha:
                      type: string
                      example: 23-12-21
                    tipo:
                      type: string
                      example: turistico
                    nombre:
                      type: string
                      example: Mauricio matuz
                    licencia:
                      type: string
                      example: LH124078108

  /api/autobus/register:
    post:
      summary: Registro de autobuses
      requestBody:
        description: Forma correcta de enviar el JSON
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clave:
                  type: string
                  example: 1LJ123s
                placa:
                  type: string
                  example: JKHA-123s
                numasientos:
                  type: integer
                  example: 401
                fecha:
                  type: string
                  example: 23-12-21
                tipo:
                  type: string
                  example: turisticos
                nombre:
                  type: string
                  example: Mauricios
                licencia:
                  type: string
                  example: LH124078108s
      responses:
        200:
          description: Registro exitoso
          content:
            application/json:
              schema:
                type: string
                example:
                  {
                    "status": true,
                    "message": "El registro se almacenó correctamente",
                  }

  /api/autobus/actualizar:
    put:
      summary: Actualizar datos de atuobuses
      requestBody:
        description: Los datos de forma ordenada
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: El ID que se usara para encontrar el autobus que se desea actualizar
                  example: 2
                clave:
                  type: string
                  example: 1LJ123S
                placa:
                  type: string
                  example: JKHA-123S
                numasientos:
                  type: integer
                  example: 401
                fecha:
                  type: string
                  example: 23-12-21
                tipo:
                  type: string
                  example: turistico
                nombre:
                  type: string
                  example: Mauricio
                licencia:
                  type: string
                  example: LH124078108S
      responses:
        200:
          description: Autobus actualizado
          content:
            application/json:
              schema:
                type: string
                example: { status: true, message: "Autobus actualizado" }

  /api/autobus/borrar:
    delete:
      summary: Borrar un autobus
      requestBody:
        description: Borrar un autobus mediante un ID
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID del autobus
                  example: 3
      responses:
        200:
          description: Contestación
          content:
            application/json:
              schema:
                type: string
                example: { status: true, message: "Autobus borrado" }
